#----------------------------------------------------------------------------------------------------
# run <main_generator.py>
#
# This program generates first round tournament pairings for a list of teams provided by the user
# The user is asked to input:
#    - number and names of teams participating in tournament
#    - number of games and season wins for each of the participating teams
#
#This file was generated by PCV on 9/2022 to practice Python fundamentals
#----------------------------------------------------------------------------------------------------
from generator import Generator

# Start an instance of class Generator
x = Generator()

# Request from the the user the number of teams that will be participating
x.get_number_teams()

# Request from the user the names for the teams that will be participating
x.get_name_teams()

# Request from the user the number of games that all participating teams have played
#   thus far in the season
x.get_number_games()

# Request the number of wins that all participating teams have had
#   thus far in the season
x.get_number_wins()

# Generate the first round tournament schedule
x.get_schedule()
